### ISSUE TITLE
Searching for replies via 3D touch menu is broken

### ISSUE THREAD

**Issue by icenode** [Squeegy/latest-chatty-2#135]
Sorry for the vague title, this one's difficult to summarise! To reproduce:

- 3D touch the Latest Chatty app icon to get the "right click" menu.
- Select 'Replies to me'
- You'll see the search results, but tapping on any thread link just opens up the same results on a new page
- Tapping the back button at the top of the app also crashes it
- Searching normally works fine

**Comment by tomkidd** [comment]
I think I know what causes this - if you've already opened the app and it's just sitting in memory in the background then if you launch "Replies to Me" from the home screen then everything works fine, but if the app isn't in memory (so, you see a gray screen for a second and then the replies to you, as opposed to the last screen you saw in the app) then you see the issue icenode describes. 

It's as if the shortcut is pushing the "Replies to Me" on the current UINavigationController but if there's not one because the app hasn't launched recently then it's trying to go "back" on a null UINavigationController and goes boom. 

If this thing is using Fabric/Crashlytics you've probably seen a thousand crashes from me alone :)

**Comment by patch-e** [comment]
Yea, that is certainly accurate with it running in the background vs. starting fresh. I had noticed that too. I haven't quite figured out how to fix it yet, but this wasn't an issue prior to iOS 11 :(

**Comment by patch-e** [comment]
Forgot to close this issue, this was fixed over a year ago :)
https://github.com/Squeegy/latest-chatty-2/commit/abdbf6c844e23bcc559c1a7fdafbefa0886bacdf
